# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'lightinnout' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lightinnout
pod 'NVActivityIndicatorView'
pod 'TextFieldEffects'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'Alamofire', '~> 4.0'
pod 'SCLAlertView'

end

target 'Widget' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Widget
    pod 'Alamofire', '~> 4.0'
    
end
